/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author 182310018
 */
public class JFAreaGerenciador extends javax.swing.JFrame {

    /**
     * Creates new form JFAreaGerenciador
     */
    public JFAreaGerenciador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EditarTreinoInstru = new javax.swing.JToggleButton();
        VerTreinoInstru = new javax.swing.JToggleButton();
        EditarInfoInstru = new javax.swing.JToggleButton();
        VerInfoInstru = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lohgo.jpg"))); // NOI18N

        EditarTreinoInstru.setBackground(new java.awt.Color(0, 0, 0));
        EditarTreinoInstru.setForeground(new java.awt.Color(255, 255, 255));
        EditarTreinoInstru.setText("Editar Treino");
        EditarTreinoInstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarTreinoInstruActionPerformed(evt);
            }
        });

        VerTreinoInstru.setBackground(new java.awt.Color(0, 0, 0));
        VerTreinoInstru.setForeground(new java.awt.Color(255, 255, 255));
        VerTreinoInstru.setText("Ver Treino");
        VerTreinoInstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTreinoInstruActionPerformed(evt);
            }
        });

        EditarInfoInstru.setBackground(new java.awt.Color(0, 0, 0));
        EditarInfoInstru.setForeground(new java.awt.Color(255, 255, 255));
        EditarInfoInstru.setText("Editar informações");
        EditarInfoInstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarInfoInstruActionPerformed(evt);
            }
        });

        VerInfoInstru.setBackground(new java.awt.Color(0, 0, 0));
        VerInfoInstru.setForeground(new java.awt.Color(255, 255, 255));
        VerInfoInstru.setText("Ver informações");
        VerInfoInstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInfoInstruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VerTreinoInstru, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(EditarInfoInstru, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(VerInfoInstru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditarTreinoInstru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(VerTreinoInstru)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(EditarTreinoInstru)
                        .addGap(18, 18, 18)
                        .addComponent(VerInfoInstru)
                        .addGap(18, 18, 18)
                        .addComponent(EditarInfoInstru)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerTreinoInstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTreinoInstruActionPerformed
        JFInfoTreino janelaT = new JFInfoTreino();
        janelaT.setVisible(true);
        janelaT.setDefaultCloseOperation(1);

    }//GEN-LAST:event_VerTreinoInstruActionPerformed

    private void EditarInfoInstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarInfoInstruActionPerformed
        JFInfoGerenciador janelaG = new JFInfoGerenciador();
        janelaG.setVisible(true);
        janelaG.setDefaultCloseOperation(1);
    }//GEN-LAST:event_EditarInfoInstruActionPerformed

    private void EditarTreinoInstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarTreinoInstruActionPerformed
        JFInfoTreino janelaT = new JFInfoTreino();
        janelaT.setVisible(true);
        janelaT.setDefaultCloseOperation(1);
    }//GEN-LAST:event_EditarTreinoInstruActionPerformed

    private void VerInfoInstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInfoInstruActionPerformed
        JFInfoGerenciador janelaG = new JFInfoGerenciador();
        janelaG.setVisible(true);
        janelaG.setDefaultCloseOperation(1);
    }//GEN-LAST:event_VerInfoInstruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAreaGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAreaGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAreaGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAreaGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAreaGerenciador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton EditarInfoInstru;
    private javax.swing.JToggleButton EditarTreinoInstru;
    private javax.swing.JToggleButton VerInfoInstru;
    private javax.swing.JToggleButton VerTreinoInstru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
